version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      args:
        NODE_ENV: development
    # ports:
    #   - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev