version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    
    watch:
      - path: ./package.json
        action: rebuild
      - path: .
        target: /app
        action: sync

    build:
      context: .
      args:
        NODE_ENV: development
    # ports:
    #   - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev