name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          image: 
          context: .
          push: true
          tags: vandanpatell/docker_test:latest

  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug SSH Key
      run: echo "${{ secrets.DOCKER_USERNAME }}"
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: SSH into server
      uses: appleboy/ssh-action@master
      with:
        host: direct.labs.play-with-docker.com
        username: ip172-18-0-21-covf7v291nsg009bc6hg
        # password: TEST
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull latest Docker image
      run: ssh ip172-18-0-21-covf7v291nsg009bc6hg@direct.labs.play-with-docker.com 'docker pull vandanpatell/docker_test:latest'

    - name: Restart Docker container
      run: ssh ip172-18-0-21-covf7v291nsg009bc6hg@direct.labs.play-with-docker.com 'docker restart nodecontainer'
